# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/diamishra/Documents/compressor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/diamishra/Documents/compressor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/Applications/CMake.app/Contents/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/diamishra/Documents/compressor/CMakeFiles /Users/diamishra/Documents/compressor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/diamishra/Documents/compressor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compressor

# Build rule for target.
compressor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compressor
.PHONY : compressor

# fast build rule for target.
compressor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/build
.PHONY : compressor/fast

#=============================================================================
# Target rules for targets named compressorTests

# Build rule for target.
compressorTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compressorTests
.PHONY : compressorTests

# fast build rule for target.
compressorTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/build
.PHONY : compressorTests/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/main.cpp.s
.PHONY : main.cpp.s

main_test.o: main_test.cpp.o
.PHONY : main_test.o

# target to build an object file
main_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/main_test.cpp.o
.PHONY : main_test.cpp.o

main_test.i: main_test.cpp.i
.PHONY : main_test.i

# target to preprocess a source file
main_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/main_test.cpp.i
.PHONY : main_test.cpp.i

main_test.s: main_test.cpp.s
.PHONY : main_test.s

# target to generate assembly for a file
main_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/main_test.cpp.s
.PHONY : main_test.cpp.s

src/compressor.o: src/compressor.cpp.o
.PHONY : src/compressor.o

# target to build an object file
src/compressor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/src/compressor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/src/compressor.cpp.o
.PHONY : src/compressor.cpp.o

src/compressor.i: src/compressor.cpp.i
.PHONY : src/compressor.i

# target to preprocess a source file
src/compressor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/src/compressor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/src/compressor.cpp.i
.PHONY : src/compressor.cpp.i

src/compressor.s: src/compressor.cpp.s
.PHONY : src/compressor.s

# target to generate assembly for a file
src/compressor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/src/compressor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/src/compressor.cpp.s
.PHONY : src/compressor.cpp.s

src/decompressor.o: src/decompressor.cpp.o
.PHONY : src/decompressor.o

# target to build an object file
src/decompressor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/src/decompressor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/src/decompressor.cpp.o
.PHONY : src/decompressor.cpp.o

src/decompressor.i: src/decompressor.cpp.i
.PHONY : src/decompressor.i

# target to preprocess a source file
src/decompressor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/src/decompressor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/src/decompressor.cpp.i
.PHONY : src/decompressor.cpp.i

src/decompressor.s: src/decompressor.cpp.s
.PHONY : src/decompressor.s

# target to generate assembly for a file
src/decompressor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/src/decompressor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/src/decompressor.cpp.s
.PHONY : src/decompressor.cpp.s

src/hashing.o: src/hashing.cpp.o
.PHONY : src/hashing.o

# target to build an object file
src/hashing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/src/hashing.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/src/hashing.cpp.o
.PHONY : src/hashing.cpp.o

src/hashing.i: src/hashing.cpp.i
.PHONY : src/hashing.i

# target to preprocess a source file
src/hashing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/src/hashing.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/src/hashing.cpp.i
.PHONY : src/hashing.cpp.i

src/hashing.s: src/hashing.cpp.s
.PHONY : src/hashing.s

# target to generate assembly for a file
src/hashing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/src/hashing.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/src/hashing.cpp.s
.PHONY : src/hashing.cpp.s

src/huffman.o: src/huffman.cpp.o
.PHONY : src/huffman.o

# target to build an object file
src/huffman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/src/huffman.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/src/huffman.cpp.o
.PHONY : src/huffman.cpp.o

src/huffman.i: src/huffman.cpp.i
.PHONY : src/huffman.i

# target to preprocess a source file
src/huffman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/src/huffman.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/src/huffman.cpp.i
.PHONY : src/huffman.cpp.i

src/huffman.s: src/huffman.cpp.s
.PHONY : src/huffman.s

# target to generate assembly for a file
src/huffman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressor.dir/build.make CMakeFiles/compressor.dir/src/huffman.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressorTests.dir/build.make CMakeFiles/compressorTests.dir/src/huffman.cpp.s
.PHONY : src/huffman.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... compressor"
	@echo "... compressorTests"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... main_test.o"
	@echo "... main_test.i"
	@echo "... main_test.s"
	@echo "... src/compressor.o"
	@echo "... src/compressor.i"
	@echo "... src/compressor.s"
	@echo "... src/decompressor.o"
	@echo "... src/decompressor.i"
	@echo "... src/decompressor.s"
	@echo "... src/hashing.o"
	@echo "... src/hashing.i"
	@echo "... src/hashing.s"
	@echo "... src/huffman.o"
	@echo "... src/huffman.i"
	@echo "... src/huffman.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

